### ISSUE TITLE
Private box protocol v2?

### ISSUE THREAD

**Issue by pietgeursen** [pietgeursen/private-box-rs#2]
Not sure if I want to copy the existing private box api which looks like:

`encrypt(plaintext, recps, max)`
`decrypt(cyphertext, skey, max)`

This api seems annoying. If patchwork were to start setting max to 20, and patchbay to 25 then patchwork users might miss out on a message if they were the 25th recipient. It's forcing the clients to agree on the max number of recipients. 

We could propose a new version of the private-box protocol that encodes the max number of recipients.
It would also be a good moment to include a version number of the private box protocol itself in the message.

Not sure how to make this backwards compatible though.

The current byte structure of a boxed message looks like:
```
[nonce bytes]
[one time pub key bytes]
[boxed key for recipients bytes] //contains the actual number of recipients of this message
[boxed message bytes]
```

...

**Comment by AljoschaMeyer** [comment]
Should we discuss this on ssb? We'll reach more interested people that way.
